spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://postgres:5432/fleetpay
    username: fleet
    password: fleet
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  port: 8080
