spring:
  application:
    name: statement-service
  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: fleetpay
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
  kafka:
    bootstrap-servers: kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  port: 8080
