spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
        - id: cards
          uri: http://card-service:8080
          predicates:
            - Path=/cards/**
        - id: tx
          uri: http://transaction-service:8080
          predicates:
            - Path=/transactions/**
        - id: statements
          uri: http://statement-service:8080
          predicates:
            - Path=/statements/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  port: 8080
