spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://postgres:5432/fleetpay
    username: fleet
    password: fleet
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  port: 8080
